# Generated by Django 5.2 on 2025-06-01 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0003_libro_usuario_resena'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='portada_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL de la portada'),
        ),
    ]
