# Generated by Django 5.2 on 2025-06-04 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0004_libro_portada_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
