# Generated by Django 5.2 on 2025-06-04 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0005_libro_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='portada_url',
        ),
        migrations.AddField(
            model_name='libro',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='portadas/'),
        ),
    ]
